// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SubscribeResponse.proto

package com.liaozl.netty.demo.serialization.protobuf;

public final class SubscribeResponseProto {
    private SubscribeResponseProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }

    public interface SubscribeResponseOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // required int32 subReqID = 1;

        /**
         * <code>required int32 subReqID = 1;</code>
         */
        boolean hasSubReqID();

        /**
         * <code>required int32 subReqID = 1;</code>
         */
        int getSubReqID();

        // required int32 respCode = 2;

        /**
         * <code>required int32 respCode = 2;</code>
         */
        boolean hasRespCode();

        /**
         * <code>required int32 respCode = 2;</code>
         */
        int getRespCode();

        // required string desc = 3;

        /**
         * <code>required string desc = 3;</code>
         */
        boolean hasDesc();

        /**
         * <code>required string desc = 3;</code>
         */
        String getDesc();

        /**
         * <code>required string desc = 3;</code>
         */
        com.google.protobuf.ByteString
        getDescBytes();
    }

    /**
     * Protobuf type {@code netty.SubscribeResponse}
     */
    public static final class SubscribeResponse extends
            com.google.protobuf.GeneratedMessage
            implements SubscribeResponseOrBuilder {
        // Use SubscribeResponse.newBuilder() to construct.
        private SubscribeResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private SubscribeResponse(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private static final SubscribeResponse defaultInstance;

        public static SubscribeResponse getDefaultInstance() {
            return defaultInstance;
        }

        public SubscribeResponse getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private SubscribeResponse(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            subReqID_ = input.readInt32();
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            respCode_ = input.readInt32();
                            break;
                        }
                        case 26: {
                            bitField0_ |= 0x00000004;
                            desc_ = input.readBytes();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return SubscribeResponseProto.internal_static_netty_SubscribeResponse_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return SubscribeResponseProto.internal_static_netty_SubscribeResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            SubscribeResponse.class, Builder.class);
        }

        public static com.google.protobuf.Parser<SubscribeResponse> PARSER =
                new com.google.protobuf.AbstractParser<SubscribeResponse>() {
                    public SubscribeResponse parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new SubscribeResponse(input, extensionRegistry);
                    }
                };

        @Override
        public com.google.protobuf.Parser<SubscribeResponse> getParserForType() {
            return PARSER;
        }

        private int bitField0_;
        // required int32 subReqID = 1;
        public static final int SUBREQID_FIELD_NUMBER = 1;
        private int subReqID_;

        /**
         * <code>required int32 subReqID = 1;</code>
         */
        public boolean hasSubReqID() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required int32 subReqID = 1;</code>
         */
        public int getSubReqID() {
            return subReqID_;
        }

        // required int32 respCode = 2;
        public static final int RESPCODE_FIELD_NUMBER = 2;
        private int respCode_;

        /**
         * <code>required int32 respCode = 2;</code>
         */
        public boolean hasRespCode() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>required int32 respCode = 2;</code>
         */
        public int getRespCode() {
            return respCode_;
        }

        // required string desc = 3;
        public static final int DESC_FIELD_NUMBER = 3;
        private Object desc_;

        /**
         * <code>required string desc = 3;</code>
         */
        public boolean hasDesc() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        /**
         * <code>required string desc = 3;</code>
         */
        public String getDesc() {
            Object ref = desc_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    desc_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string desc = 3;</code>
         */
        public com.google.protobuf.ByteString
        getDescBytes() {
            Object ref = desc_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                desc_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private void initFields() {
            subReqID_ = 0;
            respCode_ = 0;
            desc_ = "";
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) return isInitialized == 1;

            if (!hasSubReqID()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasRespCode()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasDesc()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeInt32(1, subReqID_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeInt32(2, respCode_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeBytes(3, getDescBytes());
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, subReqID_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, respCode_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(3, getDescBytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        protected Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static SubscribeResponse parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static SubscribeResponse parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static SubscribeResponse parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static SubscribeResponse parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static SubscribeResponse parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static SubscribeResponse parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static SubscribeResponse parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static SubscribeResponse parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static SubscribeResponse parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static SubscribeResponse parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(SubscribeResponse prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code netty.SubscribeResponse}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements SubscribeResponseOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return SubscribeResponseProto.internal_static_netty_SubscribeResponse_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return SubscribeResponseProto.internal_static_netty_SubscribeResponse_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                SubscribeResponse.class, Builder.class);
            }

            // Construct using com.liaozl.netty.demo.serialization.protobuf.SubscribeResponseProto.SubscribeResponse.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                subReqID_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                respCode_ = 0;
                bitField0_ = (bitField0_ & ~0x00000002);
                desc_ = "";
                bitField0_ = (bitField0_ & ~0x00000004);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return SubscribeResponseProto.internal_static_netty_SubscribeResponse_descriptor;
            }

            public SubscribeResponse getDefaultInstanceForType() {
                return SubscribeResponse.getDefaultInstance();
            }

            public SubscribeResponse build() {
                SubscribeResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public SubscribeResponse buildPartial() {
                SubscribeResponse result = new SubscribeResponse(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.subReqID_ = subReqID_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.respCode_ = respCode_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.desc_ = desc_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof SubscribeResponse) {
                    return mergeFrom((SubscribeResponse) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(SubscribeResponse other) {
                if (other == SubscribeResponse.getDefaultInstance()) return this;
                if (other.hasSubReqID()) {
                    setSubReqID(other.getSubReqID());
                }
                if (other.hasRespCode()) {
                    setRespCode(other.getRespCode());
                }
                if (other.hasDesc()) {
                    bitField0_ |= 0x00000004;
                    desc_ = other.desc_;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasSubReqID()) {

                    return false;
                }
                if (!hasRespCode()) {

                    return false;
                }
                if (!hasDesc()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                SubscribeResponse parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (SubscribeResponse) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            // required int32 subReqID = 1;
            private int subReqID_;

            /**
             * <code>required int32 subReqID = 1;</code>
             */
            public boolean hasSubReqID() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required int32 subReqID = 1;</code>
             */
            public int getSubReqID() {
                return subReqID_;
            }

            /**
             * <code>required int32 subReqID = 1;</code>
             */
            public Builder setSubReqID(int value) {
                bitField0_ |= 0x00000001;
                subReqID_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required int32 subReqID = 1;</code>
             */
            public Builder clearSubReqID() {
                bitField0_ = (bitField0_ & ~0x00000001);
                subReqID_ = 0;
                onChanged();
                return this;
            }

            // required int32 respCode = 2;
            private int respCode_;

            /**
             * <code>required int32 respCode = 2;</code>
             */
            public boolean hasRespCode() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>required int32 respCode = 2;</code>
             */
            public int getRespCode() {
                return respCode_;
            }

            /**
             * <code>required int32 respCode = 2;</code>
             */
            public Builder setRespCode(int value) {
                bitField0_ |= 0x00000002;
                respCode_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required int32 respCode = 2;</code>
             */
            public Builder clearRespCode() {
                bitField0_ = (bitField0_ & ~0x00000002);
                respCode_ = 0;
                onChanged();
                return this;
            }

            // required string desc = 3;
            private Object desc_ = "";

            /**
             * <code>required string desc = 3;</code>
             */
            public boolean hasDesc() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            /**
             * <code>required string desc = 3;</code>
             */
            public String getDesc() {
                Object ref = desc_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref)
                            .toStringUtf8();
                    desc_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>required string desc = 3;</code>
             */
            public com.google.protobuf.ByteString
            getDescBytes() {
                Object ref = desc_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    desc_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string desc = 3;</code>
             */
            public Builder setDesc(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                desc_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string desc = 3;</code>
             */
            public Builder clearDesc() {
                bitField0_ = (bitField0_ & ~0x00000004);
                desc_ = getDefaultInstance().getDesc();
                onChanged();
                return this;
            }

            /**
             * <code>required string desc = 3;</code>
             */
            public Builder setDescBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                desc_ = value;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:netty.SubscribeResponse)
        }

        static {
            defaultInstance = new SubscribeResponse(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:netty.SubscribeResponse)
    }

    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_netty_SubscribeResponse_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_netty_SubscribeResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\027SubscribeResponse.proto\022\005netty\"E\n\021Subs" +
                        "cribeResponse\022\020\n\010subReqID\030\001 \002(\005\022\020\n\010respC" +
                        "ode\030\002 \002(\005\022\014\n\004desc\030\003 \002(\tBF\n,com.liaozl.ne" +
                        "tty.demo.serialization.protobufB\026Subscri" +
                        "beResponseProto"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        internal_static_netty_SubscribeResponse_descriptor =
                                getDescriptor().getMessageTypes().get(0);
                        internal_static_netty_SubscribeResponse_fieldAccessorTable = new
                                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                                internal_static_netty_SubscribeResponse_descriptor,
                                new String[]{"SubReqID", "RespCode", "Desc",});
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
    }

    // @@protoc_insertion_point(outer_class_scope)
}
