// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SubscribeRequest.proto

package com.liaozl.netty.demo.serialization.protobuf;

public final class SubscribeRequestProto {
    private SubscribeRequestProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }

    public interface SubscribeRequestOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // required int32 subReqID = 1;

        /**
         * <code>required int32 subReqID = 1;</code>
         */
        boolean hasSubReqID();

        /**
         * <code>required int32 subReqID = 1;</code>
         */
        int getSubReqID();

        // required string userName = 2;

        /**
         * <code>required string userName = 2;</code>
         */
        boolean hasUserName();

        /**
         * <code>required string userName = 2;</code>
         */
        String getUserName();

        /**
         * <code>required string userName = 2;</code>
         */
        com.google.protobuf.ByteString
        getUserNameBytes();

        // required string productName = 3;

        /**
         * <code>required string productName = 3;</code>
         */
        boolean hasProductName();

        /**
         * <code>required string productName = 3;</code>
         */
        String getProductName();

        /**
         * <code>required string productName = 3;</code>
         */
        com.google.protobuf.ByteString
        getProductNameBytes();

        // required string phoneNumber = 4;

        /**
         * <code>required string phoneNumber = 4;</code>
         */
        boolean hasPhoneNumber();

        /**
         * <code>required string phoneNumber = 4;</code>
         */
        String getPhoneNumber();

        /**
         * <code>required string phoneNumber = 4;</code>
         */
        com.google.protobuf.ByteString
        getPhoneNumberBytes();

        // required string address = 5;

        /**
         * <code>required string address = 5;</code>
         */
        boolean hasAddress();

        /**
         * <code>required string address = 5;</code>
         */
        String getAddress();

        /**
         * <code>required string address = 5;</code>
         */
        com.google.protobuf.ByteString
        getAddressBytes();
    }

    /**
     * Protobuf type {@code netty.SubscribeRequest}
     */
    public static final class SubscribeRequest extends
            com.google.protobuf.GeneratedMessage
            implements SubscribeRequestOrBuilder {
        // Use SubscribeRequest.newBuilder() to construct.
        private SubscribeRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private SubscribeRequest(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private static final SubscribeRequest defaultInstance;

        public static SubscribeRequest getDefaultInstance() {
            return defaultInstance;
        }

        public SubscribeRequest getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private SubscribeRequest(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            subReqID_ = input.readInt32();
                            break;
                        }
                        case 18: {
                            bitField0_ |= 0x00000002;
                            userName_ = input.readBytes();
                            break;
                        }
                        case 26: {
                            bitField0_ |= 0x00000004;
                            productName_ = input.readBytes();
                            break;
                        }
                        case 34: {
                            bitField0_ |= 0x00000008;
                            phoneNumber_ = input.readBytes();
                            break;
                        }
                        case 42: {
                            bitField0_ |= 0x00000010;
                            address_ = input.readBytes();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return SubscribeRequestProto.internal_static_netty_SubscribeRequest_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return SubscribeRequestProto.internal_static_netty_SubscribeRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            SubscribeRequest.class, Builder.class);
        }

        public static com.google.protobuf.Parser<SubscribeRequest> PARSER =
                new com.google.protobuf.AbstractParser<SubscribeRequest>() {
                    public SubscribeRequest parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new SubscribeRequest(input, extensionRegistry);
                    }
                };

        @Override
        public com.google.protobuf.Parser<SubscribeRequest> getParserForType() {
            return PARSER;
        }

        private int bitField0_;
        // required int32 subReqID = 1;
        public static final int SUBREQID_FIELD_NUMBER = 1;
        private int subReqID_;

        /**
         * <code>required int32 subReqID = 1;</code>
         */
        public boolean hasSubReqID() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required int32 subReqID = 1;</code>
         */
        public int getSubReqID() {
            return subReqID_;
        }

        // required string userName = 2;
        public static final int USERNAME_FIELD_NUMBER = 2;
        private Object userName_;

        /**
         * <code>required string userName = 2;</code>
         */
        public boolean hasUserName() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>required string userName = 2;</code>
         */
        public String getUserName() {
            Object ref = userName_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    userName_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string userName = 2;</code>
         */
        public com.google.protobuf.ByteString
        getUserNameBytes() {
            Object ref = userName_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                userName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // required string productName = 3;
        public static final int PRODUCTNAME_FIELD_NUMBER = 3;
        private Object productName_;

        /**
         * <code>required string productName = 3;</code>
         */
        public boolean hasProductName() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        /**
         * <code>required string productName = 3;</code>
         */
        public String getProductName() {
            Object ref = productName_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    productName_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string productName = 3;</code>
         */
        public com.google.protobuf.ByteString
        getProductNameBytes() {
            Object ref = productName_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                productName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // required string phoneNumber = 4;
        public static final int PHONENUMBER_FIELD_NUMBER = 4;
        private Object phoneNumber_;

        /**
         * <code>required string phoneNumber = 4;</code>
         */
        public boolean hasPhoneNumber() {
            return ((bitField0_ & 0x00000008) == 0x00000008);
        }

        /**
         * <code>required string phoneNumber = 4;</code>
         */
        public String getPhoneNumber() {
            Object ref = phoneNumber_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    phoneNumber_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string phoneNumber = 4;</code>
         */
        public com.google.protobuf.ByteString
        getPhoneNumberBytes() {
            Object ref = phoneNumber_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                phoneNumber_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // required string address = 5;
        public static final int ADDRESS_FIELD_NUMBER = 5;
        private Object address_;

        /**
         * <code>required string address = 5;</code>
         */
        public boolean hasAddress() {
            return ((bitField0_ & 0x00000010) == 0x00000010);
        }

        /**
         * <code>required string address = 5;</code>
         */
        public String getAddress() {
            Object ref = address_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    address_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string address = 5;</code>
         */
        public com.google.protobuf.ByteString
        getAddressBytes() {
            Object ref = address_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                address_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private void initFields() {
            subReqID_ = 0;
            userName_ = "";
            productName_ = "";
            phoneNumber_ = "";
            address_ = "";
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) return isInitialized == 1;

            if (!hasSubReqID()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasUserName()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasProductName()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasPhoneNumber()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasAddress()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeInt32(1, subReqID_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, getUserNameBytes());
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeBytes(3, getProductNameBytes());
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                output.writeBytes(4, getPhoneNumberBytes());
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                output.writeBytes(5, getAddressBytes());
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, subReqID_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, getUserNameBytes());
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(3, getProductNameBytes());
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(4, getPhoneNumberBytes());
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(5, getAddressBytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        protected Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static SubscribeRequest parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static SubscribeRequest parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static SubscribeRequest parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static SubscribeRequest parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static SubscribeRequest parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static SubscribeRequest parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static SubscribeRequest parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static SubscribeRequest parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static SubscribeRequest parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static SubscribeRequest parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(SubscribeRequest prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code netty.SubscribeRequest}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements SubscribeRequestOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return SubscribeRequestProto.internal_static_netty_SubscribeRequest_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return SubscribeRequestProto.internal_static_netty_SubscribeRequest_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                SubscribeRequest.class, Builder.class);
            }

            // Construct using com.liaozl.netty.demo.serialization.protobuf.SubscribeRequestProto.SubscribeRequest.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                subReqID_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                userName_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                productName_ = "";
                bitField0_ = (bitField0_ & ~0x00000004);
                phoneNumber_ = "";
                bitField0_ = (bitField0_ & ~0x00000008);
                address_ = "";
                bitField0_ = (bitField0_ & ~0x00000010);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return SubscribeRequestProto.internal_static_netty_SubscribeRequest_descriptor;
            }

            public SubscribeRequest getDefaultInstanceForType() {
                return SubscribeRequest.getDefaultInstance();
            }

            public SubscribeRequest build() {
                SubscribeRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public SubscribeRequest buildPartial() {
                SubscribeRequest result = new SubscribeRequest(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.subReqID_ = subReqID_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.userName_ = userName_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.productName_ = productName_;
                if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                    to_bitField0_ |= 0x00000008;
                }
                result.phoneNumber_ = phoneNumber_;
                if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
                    to_bitField0_ |= 0x00000010;
                }
                result.address_ = address_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof SubscribeRequest) {
                    return mergeFrom((SubscribeRequest) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(SubscribeRequest other) {
                if (other == SubscribeRequest.getDefaultInstance()) return this;
                if (other.hasSubReqID()) {
                    setSubReqID(other.getSubReqID());
                }
                if (other.hasUserName()) {
                    bitField0_ |= 0x00000002;
                    userName_ = other.userName_;
                    onChanged();
                }
                if (other.hasProductName()) {
                    bitField0_ |= 0x00000004;
                    productName_ = other.productName_;
                    onChanged();
                }
                if (other.hasPhoneNumber()) {
                    bitField0_ |= 0x00000008;
                    phoneNumber_ = other.phoneNumber_;
                    onChanged();
                }
                if (other.hasAddress()) {
                    bitField0_ |= 0x00000010;
                    address_ = other.address_;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasSubReqID()) {

                    return false;
                }
                if (!hasUserName()) {

                    return false;
                }
                if (!hasProductName()) {

                    return false;
                }
                if (!hasPhoneNumber()) {

                    return false;
                }
                if (!hasAddress()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                SubscribeRequest parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (SubscribeRequest) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            // required int32 subReqID = 1;
            private int subReqID_;

            /**
             * <code>required int32 subReqID = 1;</code>
             */
            public boolean hasSubReqID() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required int32 subReqID = 1;</code>
             */
            public int getSubReqID() {
                return subReqID_;
            }

            /**
             * <code>required int32 subReqID = 1;</code>
             */
            public Builder setSubReqID(int value) {
                bitField0_ |= 0x00000001;
                subReqID_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required int32 subReqID = 1;</code>
             */
            public Builder clearSubReqID() {
                bitField0_ = (bitField0_ & ~0x00000001);
                subReqID_ = 0;
                onChanged();
                return this;
            }

            // required string userName = 2;
            private Object userName_ = "";

            /**
             * <code>required string userName = 2;</code>
             */
            public boolean hasUserName() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>required string userName = 2;</code>
             */
            public String getUserName() {
                Object ref = userName_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref)
                            .toStringUtf8();
                    userName_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>required string userName = 2;</code>
             */
            public com.google.protobuf.ByteString
            getUserNameBytes() {
                Object ref = userName_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    userName_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string userName = 2;</code>
             */
            public Builder setUserName(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                userName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string userName = 2;</code>
             */
            public Builder clearUserName() {
                bitField0_ = (bitField0_ & ~0x00000002);
                userName_ = getDefaultInstance().getUserName();
                onChanged();
                return this;
            }

            /**
             * <code>required string userName = 2;</code>
             */
            public Builder setUserNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                userName_ = value;
                onChanged();
                return this;
            }

            // required string productName = 3;
            private Object productName_ = "";

            /**
             * <code>required string productName = 3;</code>
             */
            public boolean hasProductName() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            /**
             * <code>required string productName = 3;</code>
             */
            public String getProductName() {
                Object ref = productName_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref)
                            .toStringUtf8();
                    productName_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>required string productName = 3;</code>
             */
            public com.google.protobuf.ByteString
            getProductNameBytes() {
                Object ref = productName_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    productName_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string productName = 3;</code>
             */
            public Builder setProductName(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                productName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string productName = 3;</code>
             */
            public Builder clearProductName() {
                bitField0_ = (bitField0_ & ~0x00000004);
                productName_ = getDefaultInstance().getProductName();
                onChanged();
                return this;
            }

            /**
             * <code>required string productName = 3;</code>
             */
            public Builder setProductNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                productName_ = value;
                onChanged();
                return this;
            }

            // required string phoneNumber = 4;
            private Object phoneNumber_ = "";

            /**
             * <code>required string phoneNumber = 4;</code>
             */
            public boolean hasPhoneNumber() {
                return ((bitField0_ & 0x00000008) == 0x00000008);
            }

            /**
             * <code>required string phoneNumber = 4;</code>
             */
            public String getPhoneNumber() {
                Object ref = phoneNumber_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref)
                            .toStringUtf8();
                    phoneNumber_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>required string phoneNumber = 4;</code>
             */
            public com.google.protobuf.ByteString
            getPhoneNumberBytes() {
                Object ref = phoneNumber_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    phoneNumber_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string phoneNumber = 4;</code>
             */
            public Builder setPhoneNumber(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000008;
                phoneNumber_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string phoneNumber = 4;</code>
             */
            public Builder clearPhoneNumber() {
                bitField0_ = (bitField0_ & ~0x00000008);
                phoneNumber_ = getDefaultInstance().getPhoneNumber();
                onChanged();
                return this;
            }

            /**
             * <code>required string phoneNumber = 4;</code>
             */
            public Builder setPhoneNumberBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000008;
                phoneNumber_ = value;
                onChanged();
                return this;
            }

            // required string address = 5;
            private Object address_ = "";

            /**
             * <code>required string address = 5;</code>
             */
            public boolean hasAddress() {
                return ((bitField0_ & 0x00000010) == 0x00000010);
            }

            /**
             * <code>required string address = 5;</code>
             */
            public String getAddress() {
                Object ref = address_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref)
                            .toStringUtf8();
                    address_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>required string address = 5;</code>
             */
            public com.google.protobuf.ByteString
            getAddressBytes() {
                Object ref = address_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    address_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string address = 5;</code>
             */
            public Builder setAddress(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000010;
                address_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string address = 5;</code>
             */
            public Builder clearAddress() {
                bitField0_ = (bitField0_ & ~0x00000010);
                address_ = getDefaultInstance().getAddress();
                onChanged();
                return this;
            }

            /**
             * <code>required string address = 5;</code>
             */
            public Builder setAddressBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000010;
                address_ = value;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:netty.SubscribeRequest)
        }

        static {
            defaultInstance = new SubscribeRequest(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:netty.SubscribeRequest)
    }

    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_netty_SubscribeRequest_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_netty_SubscribeRequest_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\026SubscribeRequest.proto\022\005netty\"q\n\020Subsc" +
                        "ribeRequest\022\020\n\010subReqID\030\001 \002(\005\022\020\n\010userNam" +
                        "e\030\002 \002(\t\022\023\n\013productName\030\003 \002(\t\022\023\n\013phoneNum" +
                        "ber\030\004 \002(\t\022\017\n\007address\030\005 \002(\tBE\n,com.liaozl" +
                        ".netty.demo.serialization.protobufB\025Subs" +
                        "cribeRequestProto"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        internal_static_netty_SubscribeRequest_descriptor =
                                getDescriptor().getMessageTypes().get(0);
                        internal_static_netty_SubscribeRequest_fieldAccessorTable = new
                                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                                internal_static_netty_SubscribeRequest_descriptor,
                                new String[]{"SubReqID", "UserName", "ProductName", "PhoneNumber", "Address",});
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
    }

    // @@protoc_insertion_point(outer_class_scope)
}
